version: "2"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: controlstore_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:

networks:
  mongo:
    driver: bridge
